### ISSUE TITLE
use state logo if regional logo does not exist

### ISSUE THREAD

**Issue by smayya337** [Duosmium/duosmium#1]
Regional logos default to `default.jpg` if no logo is provided. Having them default to their state logo first is preferable if it can be done.

**Comment by tctree333** [comment]
This issue has been addressed in the `duosmium-js` rewrite. (commit https://github.com/Duosmium/duosmium-js/commit/a1c955d4e101d5e8f5d4217e78fa2b8a0c838285, [link to source](https://github.com/Duosmium/duosmium-js/blob/main/utils/helpers.js#L78-L83))
