### ISSUE TITLE
Cut down on the number of tournaments that appear on the home page

### ISSUE THREAD

**Issue by smayya337** [Duosmium/duosmium#5]
Currently, `middleman` needs to generate previews for all 249 tournaments on the site. This takes a long time (~60% of total build time). Cutting that number down to, say, 12 would potentially decrease the build time by up to 50%.

**Comment by smayya337** [comment]
The switch to JS/11ty has drastically cut down on build time -- this is still probably useful as the site grows, but isn't a pressing need at the moment.

**Comment by tctree333** [comment]
It's still probably something good to do considering that the home page has ~15,400 DOM nodes when the recommended maximum is 1,500. As for search, I've [played around with Flexsearch](https://tomichen.com/blog/posts/20210608-searching-displaying-large-datasets-svelte/) before and it might be possible to get something working with the [HTML `<template>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template).
